### ISSUE TITLE
onPlayerSpawned Dupelicated functions

### ISSUE THREAD

**Issue by LostWhip** [michaeloliverx/codjumper#18]
So when using UFO, If you change teams, the functions in onPlayerSpawned dont get disabled.
If you changed teams to spectator it works as a "reset" by disabling all excess loops and respawns one iteration

watchFragButtonPressed()
{
	self endon("disconnect");
	self endon("killed_player");
	self endon("joined_spectators");

**Comment by michaeloliverx** [comment]
Fixed in #25
